services:
  app:
    build: backend/
    ports:
      - "8070:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/places
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - PLACES_API_KEY=key
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: places
    ports:
      - "5432:5432"