services:
  app:
    build: backend/
    ports:
      - "8070:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/places
      DB_USERNAME: user
      DB_PASSWORD: password
      PLACES_API_KEY: ${PLACES_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: places
    ports:
      - "5432:5432"
  
  react:
    build: frontend/
    ports:
      - "8080:5173"
    depends_on:
      - app
    environment:
      REACT_APP_API_URL: http://localhost:8070